# Basic
title: W
subtitle: Created by Wang Jianjun.
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: 欢迎来到王建军的个人博客！如有错误，可加我微信“伟大领袖毛主席教导我们说:”告知或发送邮件至wangjianjun0730@126.com
description: 成长是一条并不平坦的路
creator: <a>王建军</a>

url: "https://wangjianjun0730.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 进入Blog

# Navigation buttons in the front page.
nav:
#   - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #github: wangjianjun0730
    mail: wangjianjun0730@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
